spring.application.name=backend
server.port=8081

# Gizli bilgileri "secret" profilinden çek (application-secret.properties)
spring.profiles.include=secret

# Otomatik Tablo Oluşturma Ayarı (Büyü burada!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true